repositories:
  remote:
   - https://repo.maven.apache.org/maven2
   - https://stocksoftware.jfrog.io/stocksoftware/staging

artifacts:
  idea_codestyle: au.com.stocksoftware.idea.codestyle:idea-codestyle:xml:1.17

  javaee_api: javax:javaee-api:jar:8.0
  javax_annotation: org.realityforge.javax.annotation:javax.annotation:jar:1.0.1

  mockito_core: org.mockito:mockito-core:jar:4.5.1
  byte_buddy: net.bytebuddy:byte-buddy:jar:1.12.9
  objenesis: org.objenesis:objenesis:jar:3.2
  hamcrest: org.hamcrest:hamcrest:jar:2.2

  guiceyloops: org.realityforge.guiceyloops:guiceyloops:jar:0.112

  keycloak_core: org.keycloak:keycloak-core:jar:11.0.0
  keycloak_common: org.keycloak:keycloak-common:jar:11.0.0
  keycloak_adapter_core: org.keycloak:keycloak-adapter-core:jar:11.0.0
  keycloak_adapter_spi: org.keycloak:keycloak-adapter-spi:jar:11.0.0
