repositories:
  remote:
   - https://repo.maven.apache.org/maven2
   - https://stocksoftware.jfrog.io/stocksoftware/staging

artifacts:
  javaee_api: javax:javaee-api:jar:7.0
  javax_annotation: org.realityforge.javax.annotation:javax.annotation:jar:1.0.0

  mockito: org.mockito:mockito-all:jar:1.9.5

  guiceyloops: org.realityforge.guiceyloops:guiceyloops:jar:0.98

  keycloak_core: org.keycloak:keycloak-core:jar:2.0.0.Final
  keycloak_common: org.keycloak:keycloak-common:jar:2.0.0.Final
  keycloak_adapter_core: org.keycloak:keycloak-adapter-core:jar:2.0.0.Final
  keycloak_adapter_spi: org.keycloak:keycloak-adapter-spi:jar:2.0.0.Final
